### ISSUE TITLE
Requiem bug: while possessing a body, some things don´t drop XP

### ISSUE THREAD

**Issue by ChicheCapitalist** [Ladysnake/Requiem#160]
When possessing a body when being a demon, killing mobs doesnt give XP, and others dont event drop items, like Blazes, they dont drop XP and neither the rods. (Version 1.15.1)

**Comment by MLMII** [comment]
I believe that's because as a possessed being you no longer count as a "player", hence no XP or rare drops happen, this is why a lot of mob farms use tamed wolves as a form of automation. 

On Discord the author suggested that if one finds themselves dead and in need of a potion, hunting down and fighting a witch is an alternative method of getting the weakness effect necessary to revive.

**Comment by ChicheCapitalist** [comment]
Yeah I know, but I think that shouldnt happen, I mean it makes being an undead unbalanced and negative.

**Comment by Pyrofab** [comment]
Intended behaviour, only players can get special drops from mobs. As a compensation, you get some other drops, like music discs from being a skeleton.
We do however have plans for some kind of potion that lets you get player drops for a while.
