### ISSUE TITLE
[Weird mod conflict] Requiem-pandemonium crashes game when these 3 mods are loaded alongside.

### ISSUE THREAD

**Issue by K0-RR** [Ladysnake/Requiem#198]
Fabric Loader 0.10.8. Without Pandemonium game loads normally. If one of the mods with bold names isn't present then the game loads normally too.

Mods:
_fabric-api-0.28.0+1.16_
_modmenu-1.14.13+build.19_
requiem-1.3.0
requiem-pandemonium-1.3.0
**[1.16.4]+Flight+Rings+1.4.2**
**accurate-block-placement-1.0.8**
**bedrockify-0.2.0-1.16.2+**

crash report - https://hatebin.com/jwndniadfc
latest.log - https://hatebin.com/byynzcwzwu

**Comment by Pyrofab** [comment]
Can I get the crash report ?

**Comment by K0-RR** [comment]
Yes, sorry I forgot somehow

**Comment by K0-RR** [comment]
Should I post this on Bedrockify, Flight Rings and Accurate Block Placements githubs too?

**Comment by Pyrofab** [comment]
Ok that's indeed a weird bug, thanks for the report. It's some kind of mixin conflict, but I can't yet tell what's the cause.

**Comment by Pyrofab** [comment]
Preliminary report :

- The crashing mixin is this [`@ModifyArg`](https://github.com/Ladysnake/Requiem/blob/1.16/src/main/java/ladysnake/requiem/mixin/client/inventory/InGameHudMixin.java#L79-L89) in Requiem
- [Bedrockify](https://github.com/juancarloscp52/BedrockIfy) has a [`@Redirect`](https://github.com/juancarloscp52/BedrockIfy/blob/1.16.2%2B%2Fstable/src/main/java/me/juancarloscp52/bedrockify/mixin/client/features/screenSafeArea/InGameHudMixin.java#L54-L66) in the same place as Requiem, likely cause of the conflict
- [Flight Rings](https://github.com/tired9494/Flight-Rings) has no mixins, can't be responsible
- [Accurate Block Placement](https://github.com/orbwoi/AccurateBlockPlacement) doesn't seem to have a conflicting mixin, probably not responsible
- [Pandemonium](https://github.com/Ladysnake/Requiem/tree/1.16/expansions/pandemonium) doesn't have a conflicting mixin either, probably not responsible

Since the issue only arises when other random mods are present, I assume it's because they alter the load order.
In your log, Bedrockify is loaded latest, so I assume it works when it is loaded *before* Requiem.

I think I should be able to fix it, but it probably wouldn't hurt to inform the Bedrockify author.

Edit: it crashes when Bedrockify's mixin is loaded *after* Requiem's. I think I got a fix.
