### ISSUE TITLE
Ender dragon not taking any damage from most possessed mobs

### ISSUE THREAD

**Issue by glowmoss** [Ladysnake/Requiem#272]
Someone on the server I am on chose wandering spirit and tried beating the ender dragon but couldn't deal any damage to it. I tested further and the majority of mobs couldn't deal any damage to the dragon, even with the humanity enchantment there was no damage dealt. Please find a solution. Hopefully improve the enchantment to make the game think its player damage or something might be good.

**Comment by kestrel1110** [comment]
I chose wandering spirit too, and I can't damage it either. Definitely a bug.

**Comment by James103** [comment]
When fixing this, can you please consider only making the fix effective along with the Humanity enchantment? In other words, since the Ender Dragon can only be damaged by players (and explosions), when you are possessing a mob, you should only be able to damage the Ender Dragon using a weapon that has the Humanity enchantment on it.
