### ISSUE TITLE
Cannot load into any world with Requiem installed, but friend can

### ISSUE THREAD

**Issue by Zynovia** [Ladysnake/Requiem#279]
On Minecraft 1.16.5 using Requiem 1.5.1, Fabric API 0.33.1, Fabric Loader version 0.11.3, and Origins 0.7.0, the game loads to the main menu just fine. However, whenever I try to join a singleplayer world, or my dedicated server (which has all of the same mods), I get to "Joining world" then immediately goes to "Saving world" and gets stuck there unless I force quit the application. There may be something I'm missing, but my friend has the exact same mods and he can load into both singleplayer and the server just fine, no problems whatsoever. We both have the same versions of the mods and Fabric loader.

This issue also persists without Origins, only Fabric API and Requiem being present in the mods folder.

Here's the latest log I could find in the output:
[latest.log](https://github.com/Ladysnake/Requiem/files/6408450/latest.log)

It may very well be an issue on my end, but I have no clue what it could be. Any help would be appreciated! Apologies if it's something obvious that I might've missed.

**Comment by Pyrofab** [comment]
That's quite weird indeed, and the error is not super descriptive. Does this happen with only Requiem installed ?

**Comment by deadspidervenom** [comment]
Did a bit of research on this, the error has occured with people playing vanilla MC this was their solutions

This link the issue was in their video setting as they stated "render distance or max fps (I can't remember) was set to 0."
https://www.reddit.com/r/Minecraft/comments/kd8zt9/minecraft_crashing_when_loading_into_a_server/

In this post, it was a streaming program called "player.me" and that they suspect that other streaming programs could also cause it.
https://www.reddit.com/r/Minecraft/comments/kbhtq1/1164_worlds_not_loading/

I would suggest checking if you have anything installed and running that effects OpenGL if so shut it down and/or uninstall it, or see if any of your video settings are set too 0, as the main error i see that caused it, is that minecraft is trying to / by 0, (divide by zero), which is impossible to do.
