### ISSUE TITLE
[Request] Hardcore mode death save

### ISSUE THREAD

**Issue by ghost** [Ladysnake/Requiem#460]
I'm requesting there be a gamerule to enable/disable if hardcore mode players should be able to dissociate after they die or not. Attrition could be gained until they die permanently. I believe the old system used to work like this but now it doesn't anymore?

**Comment by Pyrofab** [comment]
The previous system was considered too easy to abuse with the mechanics added in version 2.0. Have you tried using emancipation to dissociate at will ?

**Comment by Terraphice** [comment]
+1 much later, hoping you reconsider. 

There isn't any harm in adding it as a config option, and there's clearly some demand for it. There are much better ways to handle Hardcore other than, 'the main functionality of the mod has been circumvented and this is now a small side addition rather than core gameplay feature'.

Perhaps adding a barrier to resurrection in the form of, let's say, linking to a singular vessel, and having your vessel crack upon death and requiring a more extensive repair process? (Some sort of phylactery system or something.)

Until something to make (specifically multiplayer) Hardcore a bit more fun with this mod, I think I'm going to locally fork the project and re-implement the old system for my personal use.
