### ISSUE TITLE
Self-Curing in Requiem impossible due to errors with Serilum's Collective library mod.

### ISSUE THREAD

**Issue by dalekfan** [Ladysnake/Requiem#522]
I do not know the exactly details, but I am 100% certain and have tested that the collective library mod seems to cause self-curing to be impossible, as eating a golden apple while under weakness seems to not register as a cure attempt to the game. I really hope you can look into this, because I really like a lot of Serilum's vanilla enhancing mods. You can test it out for yourself, but if you need me to send video evidence, I can.

**Comment by rwmb** [comment]
Hey, I spent an entire day testing my modpack to find this issue and it was already tracked hahaha
This is correct. When using the Serilum's Collective library mod, the weakness effect stays as weakness after eating a golden apple.
This is quite a big problem, which prevents this mod from being added to most of the existing fabric's mod-packs, since this library is used in most of them. This mod would be even more popular with this issue fixed, I believe.

**Comment by Fade-Alchemist** [comment]
The only way I have seen to self-cure is using the Dark Rites 2 addon and using the cleansing ritual. But only for 1.18.1 and below

**Comment by Eman-3600** [comment]
> The only way I have seen to self cure is using the Pandemonium addon and using the cleansing ritual.

Are you referring to the Bewitchment addon? Pandemonium only adds the wandering spirit and a config option that lets you possess mobs that have a soul.

**Comment by Fade-Alchemist** [comment]
My bad, it's Dark Rites 2 (and it is only for 1.18.1 and above)

**Comment by dalekfan** [comment]
> My bad, it's Dark Rites 2 (and it is only for 1.18.1 and above)

The bug is for Requiem, sorry for not specifying.

**Comment by Eman-3600** [comment]
Duplicates [513](https://github.com/Ladysnake/Requiem/issues/513)
