### ISSUE TITLE
Suggestion:Betweenlands mod

### ISSUE THREAD

**Issue by Caopr** [Ladysnake/Requiem#55]
No undead in the Betweenlands are able to be possessed. I dont know if it would work well as they dont operate similarly to player models at all.
Also external food [Human flesh for example] instantly decays if brought there and there is no way to get any inside the dimension itself. can be tricky if you forgot where the portal back to the overworld is. Perhaps could do something with the life crystals and the animator for returning to life?

p.s. Entering the spectre dimension from Randomthings mod leaves you completely stranded as a spirit. any mob you were controlling vanishes and you cant click to exit the box.[Edit incase anyone else has the spectre trapping problem. Just add "randomthings:spectrecore" to the list of allowed blocks for ghost so you can right click out of the dimension atleast.but youll need to exit and re-enter the world as all blocks might be unseeable and some other weird effects before possessing a mob.]

**Comment by Pyrofab** [comment]
It looks like none of the Betweenlands mobs are declared as undead by the mod. Given that Dissolution relies on that attribute, they should use it to make those mobs compatible (I could technically whitelist them, but I would rather have them confirm or deny that behaviour by setting the attribute). 

Regarding the decaying flesh, good point. I will probably play around with their API a bit. Also maybe make human flesh decay into rotten flesh instead of rotten food.

Bugs with modded dimensions splitting the player and its possessed mob are generally due to them not using Forge's recommended way of teleporting entities to other dimensions. I can't do much, sadly.
